info:
  contact: {}
  description: An example of gin
  license:
    name: MIT
  title: Golang Gin API
  version: "1.0"
paths:
  /api/public/user/register:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      summary: Register
swagger: "2.0"
