version: "3.8"
services: 
  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379/tcp"
    networks: 
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: 0.5
          memory: 50M
  db:
    image: mongo:latest
    hostname: db
    # volumes:
    #   - dbdata:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  food_app:
    container_name: food_app
    build:
      dockerfile: Dockerfile
      context: ./
    hostname: food_app
    depends_on: 
      - redis
      - db
    networks: 
      - backend
    ports:
      - "8080:8080"

networks:
  backend:
    driver: bridge

volumes:
  dbdata:
    driver_opts: 
      o: bind
      device: /Users/nguyenxuanhoangtu/Documents/projet/smartHome/server/Services/Food/data/
      type: bind
